### PR TITLE
Kernel Improvements

### PR DESCRIPTION
**Pull request by kushagra765**
***WIP***

### CODE REVIEW

**Comment by kushagra765** [comment]
I will mark it ready for review tomorrow.

**Comment by DamieFC** [comment]
Ok! Thanks!

**Review by DamieFC — APPROVED** [review]
:D

**Comment by DamieFC** [comment]
I can merge right?

**Comment by kushagra765** [comment]
Yes

**Comment by DamieFC** [comment]
Yay!

**Pull request merged**
