### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by kushagra765**
Done!

### CODE REVIEW

**Review by DamieFC — CHANGES_REQUESTED** [review]
I like most of this, although, I would like the `ports.h`/`ports.c` functions `port_byte_in()` and `port_byte_out()` to be changed to `inp()` and `outp()`, if it's not too much trouble.

**Comment by DamieFC** [comment]
Man, I wish it didn't have that red like I had a heart attack.

**Comment by kushagra765** [comment]
> I like most of this, although, I would like the `ports.h`/`ports.c` functions `port_byte_in()` and `port_byte_out()` to be changed to `inp()` and `outp()`, if it's not too much trouble.

Ok

**Comment by kushagra765** [comment]
> Man, I wish it didn't have that red like I had a heart attack.

I removed the code that wasn't required in the OS.

**Comment by kushagra765** [comment]
> I like most of this, although, I would like the `ports.h`/`ports.c` functions `port_byte_in()` and `port_byte_out()` to be changed to `inp()` and `outp()`, if it's not too much trouble.

I have changed it.

**Comment by kushagra765** [comment]
Should we implement a function like `printk()` ?

**Review by DamieFC — APPROVED** [review]
😁

**Comment by DamieFC** [comment]
Yes, we should implement something like `printk`

**Comment by kushagra765** [comment]
We need to create a `i686-elf-gcc` toolchain for the OS.

https://wiki.osdev.org/GCC_Cross-Compiler

This is important or else the OS won't work.

**Review by DamieFC — COMMENTED** [review]
Ok, I'm going to get on the cross-compiler. This is looking good! (Approve)

**Comment by kushagra765** [comment]
I will create the cross-compiler tomorrow!

**Comment by DamieFC** [comment]
Ok! Thanks!

**Comment by kushagra765** [comment]
But, you also need to create the cross-compiler on your OS to ***compile*** the OS.

**Comment by DamieFC** [comment]
Right. I'm setting that up.

**Comment by kushagra765** [comment]
The OS works now!

**Comment by kushagra765** [comment]
The Rewrite is completed. We will implement the other things after this pull request is merged.

**Comment by kushagra765** [comment]
You can test the OS by running -
1. `sh ./build.sh`
2. `qemu-system-x86_64 -kernel PlatypusOS.bin`

Do not forget to read the comments in ./build.sh !

**Comment by DamieFC** [comment]
Thank you! I'm merging it now.

**Pull request merged**
