### PR TITLE
Fixes and Improvements

### PR DESCRIPTION
**Pull request by kushagra765**
Done!

### CODE REVIEW

**Comment by DamieFC** [comment]
Thanks! Let me know when you're ready for me to merge!

**Review by DamieFC — APPROVED** [review]
:D

**Comment by kushagra765** [comment]
- Moved all .h files to include/
- Fixed .c files
- Fixed Makefile
- Updated Build Instructions

The Makefile is still not working! . Can we change the build system?

**Comment by kushagra765** [comment]
@DamieFC You can merge the pull request.

**Pull request merged**
